version: '3.8'

services:
  db:
    image: postgres:18
    container_name: fithub-db
    environment:
      POSTGRES_DB: FitHub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abacus
    ports:
      - "5432:5432"
    volumes:
      - ./FitHub_dump.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
